; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = T-ETH-Lite-ESP32S3
src_dir = examples/eth2ap

[env]
platform = espressif32@6.5.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = 
	default
	esp32_exception_decoder
build_flags = 
	-DCORE_DEBUG_LEVEL=5
board_build.partitions = huge_app.csv

[env:T-ETH-POE]
board = esp32dev
build_flags = 
	${env.build_flags}
	-DLILYGO_T_INTERNET_POE
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-POE-PRO]
board = esp32dev
build_flags = 
	${env.build_flags}
	-DLILYGO_T_ETH_POE_PRO
	-DUSER_SETUP_LOADED
	-include lib/TFT_eSPI/User_Setups/Setup216_LilyGo_ETH_Pro_ESP32.h
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-INTERNET-COM]
board = esp32dev
build_flags = 
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_INTER_COM
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-Lite-ESP32]
board = esp32dev
build_flags = 
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_ETH_LITE_ESP32
	-DUSER_SETUP_LOADED
	-include lib/TFT_eSPI/User_Setups/Setup216_LilyGo_ETH_Lite_ESP32.h
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-Lite-ESP32S3]
board = esp32s3box
build_flags = 
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_ETH_LITE_ESP32S3
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DCORE_DEBUG_LEVEL=5
	-DUSER_SETUP_LOADED
	-DST7789_DRIVER
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MOSI=3
	-DTFT_SCLK=2
	-DTFT_CS=4
	-DTFT_DC=8
	-DTFT_RST=15
	-DTFT_BL=16
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=80000000
	-DTFT_RGB_ORDER=TFT_BGR
	-DLV_COLOR_16_SWAP=1
	-DLV_TICK_CUSTOM=1
	-DLV_USE_PERF_MONITOR=1
	-DLV_DISP_DEF_REFR_PERIOD=16
	-DLV_CONF_INCLUDE_SIMPLE
	-DTOUCH_SDA=17
	-DTOUCH_SCL=18
	-DTOUCH_INT=21
	-DTOUCH_RST=38
build_src_filter = +<*>
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000
board_build.flash_mode = qio
board_build.f_cpu = 240000000
board_build.variants_dir = custom_variants
monitor_filters = 
	default
	esp32_exception_decoder
lib_ignore = 
	Network
lib_deps = 
	marian-craciunescu/ESP32Ping@^1.7.0
	lvgl/lvgl@^8.3.9
	TAMC_GT911 @ ^1.0.2

[eht_elite_base]
board = esp32s3box
build_flags = 
	${env.build_flags}
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_ETH_ELITE_ESP32S3
	-UARDUINO_USB_CDC_ON_BOOT
monitor_filters = 
	default
	esp32_exception_decoder
upload_speed = 921600
monitor_speed = 115200
lib_ignore = 
	Ethernet
lib_deps = 
	SPI
	ESP32Ping

[env:T-ETH-ELite-ESP32S3]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-LR1121]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_LR1121
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-SX1262]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_SX1262
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-SX1276]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_SX1276
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-SX1280]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_SX1280
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-SX1280PA]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_SX1280PA
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0

[env:T-ETH-ELite-ESP32S3-SX1276-TCXO]
extends = eht_elite_base
build_flags = 
	${eht_elite_base.build_flags}
	-DUSING_SX1276_TCXO
lib_deps = marian-craciunescu/ESP32Ping@^1.7.0
