[platformio]
default_envs = TAS
src_dir = main

[env:TAS]
platform = espressif32@6.5.0
board = esp32s3box
framework = arduino, espidf
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000
board_build.flash_mode = qio
board_build.f_cpu = 240000000
build_flags = 
	-DCORE_DEBUG_LEVEL=5
	-DBOARD_HAS_PSRAM
	-DLILYGO_T_ETH_LITE_ESP32S3
	-DARDUINO_USB_CDC_ON_BOOT=0
	-DUSER_SETUP_LOADED
	-DST7789_DRIVER
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MOSI=3
	-DTFT_SCLK=2
	-DTFT_CS=4
	-DTFT_DC=8
	-DTFT_RST=15
	-DTFT_BL=16
	-DTFT_BACKLIGHT_ON=HIGH
	-DSPI_FREQUENCY=80000000
	-DTFT_RGB_ORDER=TFT_BGR
	-DLV_COLOR_16_SWAP=1
	-DLV_TICK_CUSTOM=1
	-DLV_USE_PERF_MONITOR=1
	-DLV_DISP_DEF_REFR_PERIOD=16
	-DLV_CONF_INCLUDE_SIMPLE
	-Iinclude
	-include /Users/parksungjin/Project/ESP32/src/LilyGO-T-ETH-Series/lib/TFT_eSPI/User_Setups/Setup217_LilyGo_ETH_Lite_ESP32S3.h
	-DTOUCH_SDA=17
	-DTOUCH_SCL=18
	-DTOUCH_INT=21
	-DTOUCH_RST=38
	-w
lib_deps = 
	marian-craciunescu/ESP32Ping@^1.7.0
	lvgl/lvgl@^8.3.9
	TAMC_GT911 @ ^1.0.2
lib_extra_dirs = ../../lib
board_build.esp-idf.sdkconfig_defaults = sdkconfig.defaults
